### ISSUE TITLE
Proposed update to docs.

### ISSUE THREAD

**Issue by chughts** [aws-ia/cfn-ps-ibm-mq#129]
We would like to make some amendments to the documentation page. The process for this used to be to raise a pull request on the doc-edits branch, but there doesn't appear to be one. 

Can I raise a pull request with the suggested change directly into the main branch?

**Comment by vsnyc** [comment]
Following up late, but the answer is yes, any code or content updates can be raised as a pull request. 

Updates addressed in https://github.com/aws-ia/cfn-ps-ibm-mq/pull/130
